name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies and build
      run: yarn --frozen-lockfile
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ${{ github.workspace }}

  use-build2:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Display structure of downloaded files
      run: ls -R

  build:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies and build
      run: yarn --frozen-lockfile
    - name: Unit tests
      run: yarn test-unit --forbid-only
    - name: Lint code
      run: yarn lint
    - name: Lint API
      run: yarn lint-api

  integration-tests-chromium:
    strategy:
      matrix:
        node-version: [18.x]
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies and build
      run: yarn --frozen-lockfile
    - name: Install playwright
      run: npx playwright install
    - name: Integration tests (Chromium)
      run: yarn test-api-chromium --headless --forbid-only

  integration-tests-firefox:
    strategy:
      matrix:
        node-version: [18.x]
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies and build
      run: yarn --frozen-lockfile
    - name: Install playwright
      run: npx playwright install
    - name: Integration tests (Chromium)
      run: yarn test-api-firefox --headless --forbid-only
