# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x, 18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        runs-on: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.runs-on }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies and build
      run: yarn --frozen-lockfile
    - name: Unit tests
      run: yarn test-unit --forbid-only
    - name: Lint code
      run: yarn lint
    - name: Lint API
      run: yarn lint-api
